### ISSUE TITLE
MonoPhy Archived on CRAN

### ISSUE THREAD

**Issue by akiledal** [oschwery/MonoPhy#73]
It looks like MonoPhy was removed from CRAN as of  2024-04-02.

![Screenshot 2024-04-16 at 15 33 48](https://github.com/oschwery/MonoPhy/assets/31629269/5e2ad8e9-6458-4f82-b628-062144e72c52)

**Comment by oschwery** [comment]
Thanks, yes someone has already brought this to my attention (seems like I forgot to update my obsolete email associated to this package). I'm trying to have it back up again soon. In the meantime the GitHub version should do the job for most people.

**Comment by akiledal** [comment]
Thanks for looking into it!

**Comment by oschwery** [comment]
We should be back on! https://cran.r-project.org/web/packages/MonoPhy/index.html

**Comment by domivika** [comment]
Seems like MonoPhy has been archived again @oschwery.

**Comment by oschwery** [comment]
Indeed, thanks for alerting me to this, @domivika . Apparently the `taxize` package got orphaned and the dependency on it got flagged when testing `MonoPhy`. I just resubmitted a fixed version to CRAN, so hopefully it should be back up in a bit.

In the meantime, the github version should work. If you use the one I just updated (v. 1.3.2), you'll have to make sure 'taxize' is installed already.

**Comment by oschwery** [comment]
And we are back on once again! https://cran.r-project.org/web/packages/MonoPhy/index.html
